from __future__ import annotations

from typing import Any, Dict, List, Optional, TypedDict, Annotated, Union, Set, Literal
import operator

from pydantic import BaseModel, ConfigDict, Field

from nl2sql.nodes.schema.schemas import TableInfo, SchemaInfo, ForeignKey
from nl2sql.nodes.planner.schemas import (
    PlanModel, TableRef, JoinSpec, FilterSpec, ColumnRef, 
    HavingSpec, OrderSpec
)

from nl2sql.nodes.executor.schemas import ExecutionModel

from nl2sql.nodes.decomposer.schemas import DecomposerResponse, SubQuery
from nl2sql.errors import PipelineError

class GraphState(BaseModel):
    """
    State definition for the NL2SQL LangGraph pipeline.

    Attributes:
        user_query (str): The original natural language query from the user.
        plan (Optional[Dict[str, Any]]): The execution plan generated by the planner.
        sql_draft (Optional[str]): The draft SQL query generated by the generator.
        schema_info (Optional[SchemaInfo]): The retrieved schema information.
        validation (Dict[str, Any]): Validation results and capabilities.
        intent (Optional[IntentModel]): The classified intent of the query.
        execution (Optional[ExecutionModel]): The result of SQL execution.
        errors (List[PipelineError]): List of structured errors encountered.
        retry_count (int): Counter for retry attempts.
        reasoning (List[Dict[str, Any]]): Accumulated reasoning steps from nodes.
        selected_datasource_id (Optional[str]): The ID of the specifically selected datasource.
        sub_queries (Optional[List[SubQuery]]): List of structured sub-queries.
        candidate_tables (Optional[List[str]]): Pre-selected tables for this execution branch.
        intermediate_results (List[Any]): Results accumulated from parallel branches.
        query_history (List[Dict[str, Any]]): History of executed queries and results.
        final_answer (Optional[str]): The final synthesized answer returned to the user.
    """
    model_config = ConfigDict(extra="ignore", arbitrary_types_allowed=True)
    
    user_query: str = Field(description="The original natural language query from the user.")
    plan: Optional[Dict[str, Any]] = Field(default=None, description="The execution plan generated by the planner.")
    sql_draft: Optional[str] = Field(default=None, description="The draft SQL query generated by the generator.")
    schema_info: Optional[SchemaInfo] = Field(default=None, description="The retrieved schema information.")
    validation: Dict[str, Any] = Field(default_factory=dict, description="Validation results and capabilities.")

    execution: Optional[ExecutionModel] = Field(default=None, description="The result of SQL execution.")
    errors: Annotated[List[PipelineError], operator.add] = Field(default_factory=list, description="List of structured errors encountered.")
    retry_count: int = Field(default=0, description="Counter for retry attempts.")
    reasoning: Annotated[List[Dict[str, Any]], operator.add] = Field(default_factory=list, description="Accumulated reasoning steps from nodes.")
    selected_datasource_id: Optional[str] = Field(default=None, description="The ID of the specifically selected datasource.")
    sub_queries: Optional[List[SubQuery]] = Field(default=None, description="List of structured sub-queries.")
    candidate_tables: Optional[List[str]] = Field(default=None, description="Pre-selected tables for this execution branch.")
    intermediate_results: Annotated[List[Any], operator.add] = Field(default_factory=list, description="Results accumulated from parallel branches.")
    query_history: Annotated[List[Dict[str, Any]], operator.add] = Field(default_factory=list, description="History of executed queries and results.")
    final_answer: Optional[str] = Field(default=None, description="The final synthesized answer returned to the user.")
    response_type: Literal["tabular", "kpi", "summary"] = Field(default="tabular", description="The determined intent/response type for the query.")
    enriched_terms: Annotated[List[str], operator.add] = Field(default_factory=list, description="Enriched terms (keywords, entities, synonyms) for context retrieval.")
    system_events: Annotated[List[str], operator.add] = Field(default_factory=list, description="List of system events triggered (e.g. DRIFT_DETECTED).")
