from enum import Enum, auto
from typing import Optional, Any
from pydantic import BaseModel, ConfigDict

class ErrorSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class ErrorCode(str, Enum):
    MISSING_LLM = "MISSING_LLM"
    MISSING_SQL = "MISSING_SQL"
    MISSING_DATASOURCE_ID = "MISSING_DATASOURCE_ID"
    MISSING_PLAN = "MISSING_PLAN"
    INVALID_STATE = "INVALID_STATE"
    INVALID_PLAN_STRUCTURE = "INVALID_PLAN_STRUCTURE"
    SCHEMA_RETRIEVAL_FAILED = "SCHEMA_RETRIEVAL_FAILED"
    SQL_GEN_FAILED = "SQL_GEN_FAILED"
    TABLE_NOT_FOUND = "TABLE_NOT_FOUND"
    COLUMN_NOT_FOUND = "COLUMN_NOT_FOUND"
    INVALID_ALIAS_USAGE = "INVALID_ALIAS_USAGE"
    MISSING_GROUP_BY = "MISSING_GROUP_BY"
    INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT"
    INVALID_NUMERIC_VALUE = "INVALID_NUMERIC_VALUE"
    JOIN_TABLE_NOT_IN_PLAN = "JOIN_TABLE_NOT_IN_PLAN"
    JOIN_MISSING_ON_CLAUSE = "JOIN_MISSING_ON_CLAUSE"
    SECURITY_VIOLATION = "SECURITY_VIOLATION"
    SAFEGUARD_VIOLATION = "SAFEGUARD_VIOLATION"
    DB_EXECUTION_ERROR = "DB_EXECUTION_ERROR"
    EXECUTOR_CRASH = "EXECUTOR_CRASH"
    PLANNING_FAILURE = "PLANNING_FAILURE"
    VALIDATOR_CRASH = "VALIDATOR_CRASH"
    SUMMARIZER_FAILED = "SUMMARIZER_FAILED"
    PLAN_FEEDBACK = "PLAN_FEEDBACK"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    AGGREGATOR_FAILED = "AGGREGATOR_FAILED"
    PERFORMANCE_WARNING = "PERFORMANCE_WARNING"
    EXECUTION_ERROR = "EXECUTION_ERROR"
    ORCHESTRATOR_CRASH = "ORCHESTRATOR_CRASH"

class PipelineError(BaseModel):
    model_config = ConfigDict(extra="ignore")
    
    node: str
    message: str
    severity: ErrorSeverity
    error_code: ErrorCode
    stack_trace: Optional[str] = None
    details: Optional[Any] = None
